[project]
name = "lrtp-headway-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.2.2",
    "duckdb>=1.5.5",
    "marimo>=0.23.15",
    "polars[pyarrow]>=1.43.1",
    "sqlglot>=30.14.0",
    "vegafusion>=2.0.3",
]
